# Generated by Django 4.2 on 2024-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruserprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts/images'),
        ),
        migrations.AddField(
            model_name='selleruserprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts/images'),
        ),
    ]
