# Generated by Django 4.2 on 2024-09-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_car_seller_wishlist_carimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table=None,
        ),
    ]
