# Generated by Django 4.2 on 2024-09-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_car_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('url', 'time')},
        ),
    ]
