# Generated by Django 4.2 on 2024-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
