# Generated by Django 4.2 on 2024-09-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_car_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
